language: rust
dist: trusty
sudo: false

rust:
  - stable
  - beta
  - nightly

cache: cargo

matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo update
  - cargo test -vv --no-default-features --features=$FEATURE

jobs:
  include:
    - env: RUST_BACKTRACE=1 FEATURE=source
      addons:
        apt:
          packages:
            - make
    - env: RUST_BACKTRACE=1 FEATURE=system
      addons:
        apt:
          packages:
            - libfftw3-dev
    - env: RUST_BACKTRACE=1 FEATURE=intel-mkl
