language: rust
sudo: required

rust:
  - stable
  - beta
  - nightly

os:
  - linux

cache: cargo

matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo test -vv --no-default-features --features=$FEATURE

addons:
  apt:
    sources:
      - kubuntu-backports
    packages:
      - make
      - libfftw3-dev

env:
  - RUST_BACKTRACE=1 FEATURE=system
  - RUST_BACKTRACE=1 FEATURE=source
