[package]
name = "fftw"
version = "0.1.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]

[dependencies]
num-traits = "*"
lazy_static = "*"
fftw-sys = "0.1.0"

[dev-dependencies]
float-cmp = "0.2.3"
