[package]
name = "fftw"
version = "0.2.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]

description = "safe wrapper of FFTW3"
repository = "https://github.com/termoshtt/rust-fftw3"
keywords = ["fftw"]
license = "GPL-3.0"

[features]
default = ["source"]
system = ["fftw-sys/system"]
source = ["fftw-sys/source"]

[dependencies]
num-traits = "0.1.37"
num-complex = "0.1.37"
lazy_static = "0.2.2"

[dependencies.fftw-sys]
path = "fftw-sys"
version = "0.2.0"

[dev-dependencies]
float-cmp = "0.2.3"
