[package]
name = "fftw3"
version = "0.1.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]

[dependencies]
num-traits = "*"
lazy_static = "*"
fftw3-sys = { path = "fftw3-sys" }

[dev-dependencies]
float-cmp = "*"
