[package]
name = "fftw-sys"
version = "0.1.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]

description = "unsafe wrapper of FFTW3"
repository = "https://github.com/termoshtt/rust-fftw3"
keywords = ["fftw"]
license = "GPL-2.0"

[features]
default = ["source"]
system = []
source = ["fftw-src"]

[dependencies]
libc = "*"
num-complex = { git = "https://github.com/rust-num/num" }

[dependencies.fftw-src]
version = "0.1.0"
optional = true
