[package]
name = "fftw-sys"
version = "0.1.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]

description = "unsafe wrapper of FFTW3"
repository = "https://github.com/termoshtt/rust-fftw3"
keywords = ["fftw"]
license = "GPL-2.0"

[dependencies]
fftw-src = "0.1.0"
libc = "*"
num-complex = { git = "https://github.com/rust-num/num" }
