name: Rust

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        feature: ["intel-mkl", "source"]
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: >
          --all-targets
          --manifest-path=fftw/Cargo.toml
          --features=${{ matrix.feature }}
          --no-default-features

  macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        feature: ["source", "system"]
    steps:
    - uses: actions/checkout@v1
    - name: Install system FFTW
      run: brew install fftw
      if: ${{ matrix.feature == 'system' }}
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path=fftw/Cargo.toml --features=${{ matrix.feature }} --no-default-features

  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        feature: ["intel-mkl", "system", "source"]
    steps:
    - uses: actions/checkout@v1
    - name: Install system FFTW
      run: sudo apt update && sudo apt install -y libfftw3-dev
      if: ${{ matrix.feature == 'system' }}
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path=fftw/Cargo.toml --features=${{ matrix.feature }} --no-default-features

  check-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check
