[package]
name = "fftw3-src"
version = "0.1.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]

description = "Source of FFTW3"
repository = "https://github.com/termoshtt/rust-fftw3"
keywords = ["fftw"]
license = "GPL-2.0"

build = "build.rs"
links = "fftw3"

